import type { Category, Card } from './types'

export const colorCategories: Category[] = [
	{ name: 'すべて', key: 'all' },
	{ name: 'ピンク', key: 'pink' },
	{ name: 'レッド', key: 'red' },
	{ name: 'オレンジ', key: 'orange' },
	{ name: 'イエロー', key: 'yellow' },
	{ name: 'グリーン', key: 'green' },
	{ name: 'ブルー', key: 'blue' },
	{ name: 'パープル', key: 'purple' },
	{ name: 'ブラウン', key: 'brown' },
	{ name: 'モノクロ', key: 'monochrome' },
]

export const colorCards: Card[] = [
	{ id: 1, color: '#ffffff', category: ['monochrome'] },
	{ id: 2, color: '#c0c0c0', category: ['monochrome'] },
	{ id: 3, color: '#808080', category: ['monochrome'] },
	{ id: 4, color: '#404040', category: ['monochrome'] },
	{ id: 5, color: '#000000', category: ['monochrome'] },
	{ id: 6, color: '#fab3b2', category: ['pink'] },
	{ id: 7, color: '#fbcbb3', category: ['pink', 'orange'] },
	{ id: 8, color: '#fcd8b4', category: ['orange'] },
	{ id: 9, color: '#fdebb4', category: ['yellow'] },
	{ id: 10, color: '#fffeb5', category: ['yellow'] },
	{ id: 11, color: '#e1fdb6', category: ['green'] },
	{ id: 12, color: '#c6fbb6', category: ['green'] },
	{ id: 13, color: '#c7fcda', category: ['green'] },
	{ id: 14, color: '#c7fcff', category: ['blue'] },
	{ id: 15, color: '#c2eafe', category: ['blue'] },
	{ id: 16, color: '#bdd8fe', category: ['blue'] },
	{ id: 17, color: '#b8c6fd', category: ['purple'] },
	{ id: 18, color: '#b4b4fd', category: ['purple'] },
	{ id: 19, color: '#d2b6fd', category: ['purple'] },
	{ id: 20, color: '#f1b8fd', category: ['pink'] },
	{ id: 21, color: '#f1b8d8', category: ['pink'] },
	{ id: 22, color: '#e87267', category: ['red'] },
	{ id: 23, color: '#ed9e69', category: ['orange'] },
	{ id: 24, color: '#f0b66b', category: ['orange'] },
	{ id: 25, color: '#f6da6d', category: ['yellow'] },
	{ id: 26, color: '#fefd71', category: ['yellow'] },
	{ id: 27, color: '#c6fb70', category: ['green'] },
	{ id: 28, color: '#98f970', category: ['green'] },
	{ id: 29, color: '#99fab6', category: ['green'] },
	{ id: 30, color: '#9bfbff', category: ['blue'] },
	{ id: 31, color: '#8cd6fe', category: ['blue'] },
	{ id: 32, color: '#7eb2fd', category: ['blue'] },
	{ id: 33, color: '#738efc', category: ['blue'] },
	{ id: 34, color: '#6a6bfb', category: ['blue'] },
	{ id: 35, color: '#a86ffc', category: ['purple'] },
	{ id: 36, color: '#e976fc', category: ['pink'] },
	{ id: 37, color: '#e873b2', category: ['pink'] },
	{ id: 38, color: '#e4390d', category: ['red'] },
	{ id: 39, color: '#e76414', category: ['orange'] },
	{ id: 40, color: '#ea881b', category: ['orange'] },
	{ id: 41, color: '#f2c228', category: ['orange'] },
	{ id: 42, color: '#fefd35', category: ['yellow'] },
	{ id: 43, color: '#a6fa33', category: ['green'] },
	{ id: 44, color: '#7ff932', category: ['green'] },
	{ id: 45, color: '#7ff986', category: ['green'] },
	{ id: 46, color: '#82faff', category: ['blue'] },
	{ id: 47, color: '#62befd', category: ['blue'] },
	{ id: 48, color: '#4481fc', category: ['blue'] },
	{ id: 49, color: '#2947fb', category: ['blue'] },
	{ id: 50, color: '#1c21fb', category: ['blue'] },
	{ id: 51, color: '#752bfb', category: ['purple'] },
	{ id: 52, color: '#e643fb', category: ['pink', 'purple'] },
	{ id: 53, color: '#e43b7f', category: ['pink'] },
	{ id: 54, color: '#881e04', category: ['brown', 'red'] },
	{ id: 55, color: '#8a3b08', category: ['brown'] },
	{ id: 56, color: '#8c510c', category: ['brown'] },
	{ id: 57, color: '#917413', category: ['brown'] },
	{ id: 58, color: '#98981c', category: ['brown', 'green'] },
	{ id: 59, color: '#63961a', category: ['green'] },
	{ id: 60, color: '#49951a', category: ['green'] },
	{ id: 61, color: '#4a9551', category: ['green'] },
	{ id: 62, color: '#4b9699', category: ['blue'] },
	{ id: 63, color: '#387198', category: ['blue'] },
	{ id: 64, color: '#264d97', category: ['blue'] },
	{ id: 65, color: '#162b97', category: ['blue'] },
	{ id: 66, color: '#0c0f96', category: ['blue'] },
	{ id: 67, color: '#461697', category: ['purple'] },
	{ id: 68, color: '#892497', category: ['purple'] },
	{ id: 69, color: '#89204c', category: ['purple', 'red'] },
	{ id: 70, color: '#440a01', category: ['brown'] },
	{ id: 71, color: '#451e02', category: ['brown'] },
	{ id: 72, color: '#462903', category: ['brown'] },
	{ id: 73, color: '#493a05', category: ['brown'] },
	{ id: 74, color: '#4d4c09', category: ['brown', 'green'] },
	{ id: 75, color: '#324b08', category: ['green'] },
	{ id: 76, color: '#224b08', category: ['green'] },
	{ id: 77, color: '#224b29', category: ['green'] },
	{ id: 78, color: '#234b4d', category: ['green', 'blue'] },
	{ id: 79, color: '#19394c', category: ['blue'] },
	{ id: 80, color: '#10274c', category: ['blue'] },
	{ id: 81, color: '#08154c', category: ['blue'] },
	{ id: 82, color: '#03044c', category: ['blue'] },
	{ id: 83, color: '#23064c', category: ['blue', 'purple'] },
	{ id: 84, color: '#440d4c', category: ['purple'] },
	{ id: 85, color: '#440b26', category: ['purple'] },
	// ... 他のカード
]
